# SPDX-License-Identifier: MPL-2.0
# (MPL-2.0 is automatic legal fallback until PMPL is formally recognised)

[package]
name = "reversibility-cluster-compose"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "reversibility-cluster-compose"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
